apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-rbac

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: demo-acm, operator: In, values: ["yes"]}