apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: demo-acm

placementRef:
  name: demo-acm
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:

- name: demo-rbac
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: demo-networkpolicy
  kind: Policy
  apiGroup: policy.open-cluster-management.io